{% set name = "units" %}
{% set version = "0.07" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/units-{{ version }}.tar.gz
  sha256: 43eb3e073e1b11289df7b1c3f184b5b917ccad178b717b03933298716f200e14

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - units
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://bitbucket.org/adonohue/units/
  summary: Python support for quantities with units
  license: BSD-3-Clause
  license_file: units/LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
